export const HOME_ROUTE = 'HOME';
export const LEADERBOARD_ROUTE = 'LEADERBOARD';
export const NEW_GAME_ROUTE = 'NEW_GAME';
export const SETTINGS_ROUTE = 'SETTINGS';
export const SETTINGS_NATIVE_ROUTE = 'SETTINGS_NATIVE';
export const SETTINGS_WEB_ROUTE = 'SETTINGS_WEB';
